### ISSUE TITLE
硬件可以识别了，tvh里应该如何配置呢？

### ISSUE THREAD

**Issue by manhere** [hanwckf/hd2312#1]
没有DTMB的选项，使用DVB-T替代？
有劳指教下。

**Comment by hanwckf** [comment]
是的，直接按DVB-T设置，除了频率以外的其他所有解调设置都设置为AUTO即可

**Comment by hanwckf** [comment]
![image](https://github.com/user-attachments/assets/6b910c0e-6d86-4981-a0f6-3d4be038e68f)
