### ISSUE TITLE
Build failed on openwrt ipq40xx platform

### ISSUE THREAD

**Issue by wheretoteardown** [hanwckf/hd2312#2]
按照说明步骤添加Makefile，平台IPQ40xx，设备CM520-79f，内核5.10.220，编译lede源码来自
coolsnowwolf/lede
错误如下
find /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/wireless-regdb-2022.08.12/ipkg-all/wireless-regdb -name 'CVS' -o -name '.svn' -o -name '.#*' -o -name '*~'| xargs -r rm -rf
export CROSS="arm-openwrt-linux-muslgnueabi-"  NO_RENAME=1 ; NM="arm-openwrt-linux-muslgnueabi-nm" STRIP="/mnt/sda1/code/lede/staging_dir/host/bin/sstrip -z" STRIP_KMOD="/mnt/sda1/code/lede/scripts/strip-kmod.sh" PATCHELF="/mnt/sda1/code/lede/staging_dir/host/bin/patchelf" /mnt/sda1/code/lede/scripts/rstrip.sh /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/wireless-regdb-2022.08.12/ipkg-all/wireless-regdb
(cd /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/wireless-regdb-2022.08.12/ipkg-all/wireless-regdb/CONTROL; ( echo "$CONTROL"; printf "Description: "; echo "$DESCRIPTION" | sed -e 's,^[[:space:]]*, ,g'; ) > control; chmod 644 control; ( echo "#!/bin/sh"; echo "[ \"\${IPKG_NO_SCRIPT}\" = \"1\" ] && exit 0"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_postinst \$0 \$@"; ) > postinst; ( echo "#!/bin/sh"; echo "[ -s "\${IPKG_INSTROOT}/lib/functions.sh" ] || exit 0"; echo ". \${IPKG_INSTROOT}/lib/functions.sh"; echo "default_prerm \$0 \$@"; ) > prerm; chmod 0755 postinst prerm;  )
install -d -m0755 /mnt/sda1/code/lede/bin/packages/arm_cortex-a7_neon-vfpv4/base
/mnt/sda1/code/lede/staging_dir/host/bin/fakeroot /mnt/sda1/code/lede/staging_dir/host/bin/bash /mnt/sda1/code/lede/scripts/ipkg-build -m "" /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/wireless-regdb-2022.08.12/ipkg-all/wireless-regdb /mnt/sda1/code/lede/bin/packages/arm_cortex-a7_neon-vfpv4/base
Packaged contents of /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/wireless-regdb-2022.08.12/ipkg-all/wireless-regdb into /mnt/sda1/code/lede/bin/packages/arm_cortex-a7_neon-vfpv4/base/wireless-regdb_2022.08.12-1_all.ipk
echo "wireless-regdb" >> /mnt/sda1/code/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/pkginfo/wireless-regdb.default.install
make[3]: Leaving directory '/mnt/sda1/code/lede/package/firmware/wireless-regdb'
time: package/firmware/wireless-regdb/compile#0.48#0.16#0.59
make[3]: Entering directory '/mnt/sda1/code/lede/package/hd2312'
touch /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/.prepared_149d9e1eab41109520c3fe93aa0de123_6664517399ebbbc92a37c5bb081b5c53_check
. /mnt/sda1/code/lede/include/shell.sh; xzcat /mnt/sda1/code/lede/dl/dvb-hd2312-1.0.tar.xz | tar -C /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/.. -xf -
[ ! -d ./src/ ] || cp -fpR ./src/. /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0
touch /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/.prepared_149d9e1eab41109520c3fe93aa0de123_6664517399ebbbc92a37c5bb081b5c53
rm -f /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/.configured_*
rm -f /mnt/sda1/code/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.hd2312_installed
(cd /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/./; if [ -x ./configure ]; then find /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/ -name config.guess | xargs -r chmod u+w; find /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/ -name config.guess | xargs -r -n1 cp --remove-destination /mnt/sda1/code/lede/scripts/config.guess; find /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/ -name config.sub | xargs -r chmod u+w; find /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/ -name config.sub | xargs -r -n1 cp --remove-destination /mnt/sda1/code/lede/scripts/config.sub; AR="arm-openwrt-linux-muslgnueabi-gcc-ar" AS="arm-openwrt-linux-muslgnueabi-gcc -c -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -mfloat-abi=hard -fmacro-prefix-map=/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0=dvb-hd2312-1.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro" LD=arm-openwrt-linux-muslgnueabi-ld NM="arm-openwrt-linux-muslgnueabi-gcc-nm" CC="arm-openwrt-linux-muslgnueabi-gcc" GCC="arm-openwrt-linux-muslgnueabi-gcc" CXX="arm-openwrt-linux-muslgnueabi-g++" RANLIB="arm-openwrt-linux-muslgnueabi-gcc-ranlib" STRIP=arm-openwrt-linux-muslgnueabi-strip OBJCOPY=arm-openwrt-linux-muslgnueabi-objcopy OBJDUMP=arm-openwrt-linux-muslgnueabi-objdump SIZE=arm-openwrt-linux-muslgnueabi-size CFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -mfloat-abi=hard -fmacro-prefix-map=/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0=dvb-hd2312-1.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220/drivers/media/usb/dvb-usb -I/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220/drivers/media/dvb-frontends" CXXFLAGS="-Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -mfloat-abi=hard -fmacro-prefix-map=/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0=dvb-hd2312-1.0 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220/drivers/media/usb/dvb-usb -I/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220/drivers/media/dvb-frontends" CPPFLAGS="-I/mnt/sda1/code/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/usr/include -I/mnt/sda1/code/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/include/fortify -I/mnt/sda1/code/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/include " LDFLAGS="-L/mnt/sda1/code/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/usr/lib -L/mnt/sda1/code/lede/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-11.3.0_musl_eabi/lib -znow -zrelro "   ./configure --target=arm-openwrt-linux --host=arm-openwrt-linux --build=x86_64-pc-linux-gnu --program-prefix="" --program-suffix="" --prefix=/usr --exec-prefix=/usr --bindir=/usr/bin --sbindir=/usr/sbin --libexecdir=/usr/lib --sysconfdir=/etc --datadir=/usr/share --localstatedir=/var --mandir=/usr/man --infodir=/usr/info --disable-nls  ; fi; )
touch /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/.configured_68b329da9893e34099c7d8ad5cb9c940
rm -f /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/.built
touch /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/.built_check
make -C /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220 KCFLAGS="-fmacro-prefix-map=/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi=target-arm_cortex-a7+neon-vfpv4_musl_eabi -fno-caller-saves " HOSTCFLAGS="-O2 -I/mnt/sda1/code/lede/staging_dir/host/include -I/mnt/sda1/code/lede/staging_dir/hostpkg/include -I/mnt/sda1/code/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/host/include -Wall -Wmissing-prototypes -Wstrict-prototypes" CROSS_COMPILE="arm-openwrt-linux-muslgnueabi-" ARCH="arm" KBUILD_HAVE_NLS=no KBUILD_BUILD_USER="" KBUILD_BUILD_HOST="" KBUILD_BUILD_TIMESTAMP="Tue Aug 20 09:34:00 2024" KBUILD_BUILD_VERSION="0" KBUILD_HOSTLDFLAGS="-L/mnt/sda1/code/lede/staging_dir/host/lib" CONFIG_SHELL="bash" V=''  cmd_syscalls= KBUILD_EXTRA_SYMBOLS="/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/symvers/cryptodev-linux.symvers /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/symvers/fast-classifier.symvers /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/symvers/fullconenat.symvers /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/symvers/shortcut-fe.symvers" KERNELRELEASE=5.10.220 CC="arm-openwrt-linux-muslgnueabi-gcc" M=/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0 EXTRA_CFLAGS="-I/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220/drivers/media/usb/dvb-usb -I/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220/drivers/media/dvb-frontends" CONFIG_DVB_USB=y modules
make[4]: Entering directory '/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220'
  CC [M]  /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/hdic_hd2312.o
  LD [M]  /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/hd2312.o
  CC [M]  /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/hd2312-fe.o
  MODPOST /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/Module.symvers
ERROR: modpost: "dvb_usb_device_exit" [/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/hd2312.ko] undefined!
ERROR: modpost: "dvb_usb_device_init" [/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/hd2312.ko] undefined!
make[5]: *** [scripts/Makefile.modpost:123: /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/Module.symvers] Error 1
make[5]: *** Deleting file '/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/Module.symvers'
make[4]: *** [Makefile:1759: modules] Error 2
make[4]: Leaving directory '/mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220'
make[3]: *** [Makefile:40: /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/dvb-hd2312-1.0/.built] Error 2
make[3]: Leaving directory '/mnt/sda1/code/lede/package/hd2312'
time: package/hd2312/compile#1.51#0.34#1.84
    ERROR: package/hd2312 failed to build.
make[2]: *** [package/Makefile:116: package/hd2312/compile] Error 1
make[2]: Leaving directory '/mnt/sda1/code/lede'
make[1]: *** [package/Makefile:110: /mnt/sda1/code/lede/staging_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/stamp/.package_compile] Error 2
make[1]: Leaving directory '/mnt/sda1/code/lede'
make: *** [/mnt/sda1/code/lede/include/toplevel.mk:231: world] Error 2

**Comment by hanwckf** [comment]
请直接使用make命令编译完整固件，不要单独编译

**Comment by wheretoteardown** [comment]
> 请直接使用make命令编译完整固件，不要单独编译

使用make命令编译完整固件，这是截取最后的一段错误代码。先用make -j4 V=s编译直接报错，之后执行dirclean再用make -j1 V=s编译，提示hd2312有个ko文件未定义。

**Comment by hanwckf** [comment]
看一下`cat /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220/.config | grep DVB_USB`的具体内容

**Comment by wheretoteardown** [comment]
> 看一下`cat /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220/.config | grep DVB_USB`的具体内容

输入这个命令未返回任何内容，grep DVB也没有内容，grep USB内容如下
.config | grep USB
# CONFIG_MISC_RTSX_USB is not set
# CONFIG_MDIO_MVUSB is not set
# CONFIG_USB_NET_DRIVERS is not set
# CONFIG_I2C_TINY_USB is not set
# USB GPIO expanders
# end of USB GPIO expanders
# USB-based Watchdog Cards
# CONFIG_USBPCWATCHDOG is not set
# CONFIG_REGULATOR_QCOM_USB_VBUS is not set
# CONFIG_IR_MCEUSB is not set
# CONFIG_IR_IGORPLUGUSB is not set
# CONFIG_IR_TTUSBIR is not set
# USB HID support
# CONFIG_USB_HID is not set
# USB HID Boot Protocol drivers
# CONFIG_USB_KBD is not set
# CONFIG_USB_MOUSE is not set
# end of USB HID Boot Protocol drivers
# end of USB HID support
CONFIG_USB_OHCI_LITTLE_ENDIAN=y
CONFIG_USB_SUPPORT=y
CONFIG_USB_COMMON=y
# CONFIG_USB_LED_TRIG is not set
# CONFIG_USB_ULPI_BUS is not set
# CONFIG_USB_CONN_GPIO is not set
CONFIG_USB_ARCH_HAS_HCD=y
CONFIG_USB=y
CONFIG_USB_PCI=y
# CONFIG_USB_ANNOUNCE_NEW_DEVICES is not set
# Miscellaneous USB options
CONFIG_USB_DEFAULT_PERSIST=y
# CONFIG_USB_FEW_INIT_RETRIES is not set
# CONFIG_USB_DYNAMIC_MINORS is not set
# CONFIG_USB_OTG_PRODUCTLIST is not set
# CONFIG_USB_OTG_DISABLE_EXTERNAL_HUB is not set
CONFIG_USB_LEDS_TRIGGER_USBPORT=m
CONFIG_USB_AUTOSUSPEND_DELAY=2
# CONFIG_USB_MON is not set
# USB Host Controller Drivers
# CONFIG_USB_C67X00_HCD is not set
CONFIG_USB_XHCI_HCD=m
# CONFIG_USB_XHCI_DBGCAP is not set
CONFIG_USB_XHCI_PCI=m
# CONFIG_USB_XHCI_PCI_RENESAS is not set
CONFIG_USB_XHCI_PLATFORM=m
# CONFIG_USB_EHCI_HCD is not set
# CONFIG_USB_OXU210HP_HCD is not set
# CONFIG_USB_ISP116X_HCD is not set
# CONFIG_USB_FOTG210_HCD is not set
# CONFIG_USB_MAX3421_HCD is not set
# CONFIG_USB_OHCI_HCD is not set
# CONFIG_USB_UHCI_HCD is not set
# CONFIG_USB_SL811_HCD is not set
# CONFIG_USB_R8A66597_HCD is not set
# CONFIG_USB_HCD_TEST_MODE is not set
# USB Device Class drivers
# CONFIG_USB_ACM is not set
# CONFIG_USB_PRINTER is not set
# CONFIG_USB_WDM is not set
# CONFIG_USB_TMC is not set
# NOTE: USB_STORAGE depends on SCSI but BLK_DEV_SD may
# also be needed; see USB_STORAGE Help for more info
# USB Imaging devices
# CONFIG_USB_MDC800 is not set
# CONFIG_USBIP_CORE is not set
# CONFIG_USB_CDNS3 is not set
# CONFIG_USB_MUSB_HDRC is not set
CONFIG_USB_DWC3=m
CONFIG_USB_DWC3_HOST=y
# CONFIG_USB_DWC3_HAPS is not set
# CONFIG_USB_DWC3_OF_SIMPLE is not set
CONFIG_USB_DWC3_QCOM=m
# CONFIG_USB_DWC2 is not set
# CONFIG_USB_ISP1760 is not set
# USB port drivers
# CONFIG_USB_SERIAL is not set
# USB Miscellaneous drivers
# CONFIG_USB_EMI62 is not set
# CONFIG_USB_EMI26 is not set
# CONFIG_USB_ADUTUX is not set
# CONFIG_USB_SEVSEG is not set
# CONFIG_USB_LEGOTOWER is not set
# CONFIG_USB_LCD is not set
# CONFIG_USB_CYPRESS_CY7C63 is not set
# CONFIG_USB_CYTHERM is not set
# CONFIG_USB_IDMOUSE is not set
# CONFIG_USB_FTDI_ELAN is not set
# CONFIG_USB_APPLEDISPLAY is not set
# CONFIG_USB_LD is not set
# CONFIG_USB_TRANCEVIBRATOR is not set
# CONFIG_USB_IOWARRIOR is not set
# CONFIG_USB_TEST is not set
# CONFIG_USB_EHSET_TEST_FIXTURE is not set
# CONFIG_USB_ISIGHTFW is not set
# CONFIG_USB_YUREX is not set
# CONFIG_USB_EZUSB_FX2 is not set
# CONFIG_USB_HUB_USB251XB is not set
# CONFIG_USB_HSIC_USB3503 is not set
# CONFIG_USB_HSIC_USB4604 is not set
# CONFIG_USB_LINK_LAYER_TEST is not set
# CONFIG_USB_CHAOSKEY is not set
# USB Physical Layer drivers
# CONFIG_NOP_USB_XCEIV is not set
# CONFIG_USB_GPIO_VBUS is not set
# CONFIG_USB_ISP1301 is not set
# CONFIG_USB_ULPI is not set
# end of USB Physical Layer drivers
# CONFIG_USB_GADGET is not set
# CONFIG_USB_ROLE_SWITCH is not set
# LED driver for blink(1) USB RGB LED is under Special HID drivers (HID_THINGM)
# CONFIG_EXTCON_USB_GPIO is not set
# CONFIG_BCM_KONA_USB2_PHY is not set
# CONFIG_PHY_FSL_IMX8MQ_USB is not set
# CONFIG_PHY_PXA_28NM_USB2 is not set
CONFIG_PHY_QCOM_IPQ4019_USB=y
# CONFIG_PHY_QCOM_QUSB2 is not set
# CONFIG_PHY_QCOM_USB_SNPS_FEMTO_V2 is not set
# CONFIG_PHY_QCOM_USB_HS_28NM is not set
# CONFIG_PHY_QCOM_USB_SS is not set
# CONFIG_PHY_QCOM_IPQ806X_USB is not set
# CONFIG_USB4 is not set

**Comment by wheretoteardown** [comment]
另外查看lede目录下的.config文件如下
cat .config | grep DVB
# DVB Drivers
# end of DVB Drivers
# DVB Support
# end of DVB Support
CONFIG_TVHEADEND_LINUXDVB_SUPPORT=y
CONFIG_TVHEADEND_DVBSCAN_SUPPORT=y
# DVB descrambling and some codecs are only available with BUILD_PATENTED.

**Comment by wheretoteardown** [comment]
> 看一下`cat /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220/.config | grep DVB_USB`的具体内容
输入这个命令查看，在build_dir内核目录下的.config，没有找到任何DVB相关内容，改成小写的dvb也没有任何内容
另外查看lede目录下的.config文件如下
cat .config | grep DVB

DVB Drivers
end of DVB Drivers
DVB Support
end of DVB Support
CONFIG_TVHEADEND_LINUXDVB_SUPPORT=y
CONFIG_TVHEADEND_DVBSCAN_SUPPORT=y

DVB descrambling and some codecs are only available with BUILD_PATENTED.
改成小写
cat .config | grep dvb
cat .config | grep dvb
CONFIG_PACKAGE_kmod-dvb-core=y
CONFIG_PACKAGE_kmod-dvb-usb=y
CONFIG_PACKAGE_kmod-dvb-hd2312=y

**Comment by wheretoteardown** [comment]
> 看一下`cat /mnt/sda1/code/lede/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/linux-ipq40xx_generic/linux-5.10.220/.config | grep DVB_USB`的具体内容

输入这个命令查看，在build_dir内核目录下的.config，没有找到任何DVB相关内容，改成小写的dvb也没有任何内容
另外查看lede目录下的.config文件如下
cat .config | grep DVB

DVB Drivers
end of DVB Drivers
DVB Support
end of DVB Support
CONFIG_TVHEADEND_LINUXDVB_SUPPORT=y
CONFIG_TVHEADEND_DVBSCAN_SUPPORT=y

DVB descrambling and some codecs are only available with BUILD_PATENTED.
改成小写
cat .config | grep dvb
cat .config | grep dvb
CONFIG_PACKAGE_kmod-dvb-core=y
CONFIG_PACKAGE_kmod-dvb-usb=y
CONFIG_PACKAGE_kmod-dvb-hd2312=y

**Comment by wheretoteardown** [comment]
执行make kernel_menuconfig，内核配置菜单手动选择那几项DVB驱动支持，保存设置后再次编译，成功了
